### ISSUE TITLE
Issues with Airspeed during installation

### ISSUE THREAD

**Issue by MaxLevianSterling** [ChristophReich1996/Cell-DETR#15]
On the last line of the installation code
`(venv) maxs@doraemon1:~/Cell-DETR/pade_activation_unit/cuda$ python setup.py build install`

I get:
`Traceback (most recent call last):
  File "setup.py", line 301, in <module>
    generate_cpp_module(fname='pau_cuda.cpp')
  File "setup.py", line 51, in generate_cpp_module
    content = file_content.merge(locals())
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 95, in merge
    self.merge_to(namespace, output, loader)
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 105, in merge_to
    self.ensure_compiled()
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 100, in ensure_compiled
    self.root_element = TemplateBody(self.filename, self.content)
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 270, in __init__
    self.parse()
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 1245, in parse
    self.block = self.next_element(Block)
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 314, in next_element
    element = element_spec(self.filename, self._full_text, self.end)
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 270, in __init__
    self.parse()
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 1277, in parse
    FallthroughHashText)))
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 321, in next_element
    self.end)
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 270, in __init__
    self.parse()
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 1033, in parse
    self.require_match(self.OPEN_PAREN, '(')
  File "/home/maxs/.virtualenvs/venv/lib/python3.6/site-packages/airspeed/__init__.py", line 308, in require_match
    raise self.syntax_error(expected)
airspeed.TemplateSyntaxError: line 6, column 8: expected ( in define definition, got:  CHECK_CUDA(x) AT_ASSERTM(x.type().i ... ...`

I thought the issue was with the Airspeed library / cuda combination, but I've updated both. **The setup.py file has an airspeed template that doesn't match the expectations of airspeed itself.** Have you any idea where I should look for the problem? I can't find a single thing about this problem anywhere. Do I need a specific older version of Airspeed?

Thanks in advance for reading this message,
Max

**Comment by HUiTUi** [comment]
I encounter the same questions? Do you have fixed this problem?
