### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ranck626** [ChristophReich1996/Cell-DETR#17]
Traceback (most recent call last):
  File "main.py", line 150, in <module>
    model_wrapper.test()
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/content/drive/MyDrive/Cell-DETR/model_wrapper.py", line 421, in test
    misc.plot_instance_segmentation_labels(
  File "/content/drive/MyDrive/Cell-DETR/misc.py", line 435, in plot_instance_segmentation_labels
    instances_map += np.array(colors_traps[min(counter_trap_instance, len(colors_cells) - 1)]).reshape(1, 1, 3) \
IndexError: tuple index out of range

**Comment by ranck626** [comment]
This problem sometimes appears and sometimes does not. weird
